import type { Category, MenuItem } from './types';

export const CATEGORIES: Category[] = [
  { id: 'cat1', name: 'Entradas', order: 1, isVisible: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'cat2', name: 'Parrilla', order: 2, isVisible: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'cat3', name: 'Acompañamientos', order: 3, isVisible: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'cat4', name: 'Postres', order: 4, isVisible: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'cat5', name: 'Bebidas', order: 5, isVisible: true, createdAt: new Date(), updatedAt: new Date() },
  { id: 'cat6', name: 'Vinos', order: 6, isVisible: true, createdAt: new Date(), updatedAt: new Date() },
];

export const MENU_ITEMS: MenuItem[] = [
  // Entradas
  {
    id: 'item1',
    name: 'Empanada de Carne',
    description: 'Clásica empanada argentina de carne cortada a cuchillo.',
    price: 1500,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageId: 'entrada-1',
    categoryId: 'cat1',
    isVisible: true,
    inStock: true,
    isSpecial: false,
    tags: [],
    allergens: ['gluten'],
    searchKeywords: ['empanada', 'carne', 'entrada'],
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item2',
    name: 'Provoleta a la Parrilla',
    description: 'Queso provolone grillado con orégano y aceite de oliva.',
    price: 4500,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/201/600/400',
    imageId: 'entrada-2',
    tags: ['sin TACC', 'veggie'],
    allergens: ['lacteos'],
    searchKeywords: ['provoleta', 'queso', 'parrilla', 'veggie'],
    categoryId: 'cat1',
    isVisible: true,
    inStock: true,
    isSpecial: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Parrilla
  {
    id: 'item3',
    name: 'Bife de Chorizo',
    description: 'Corte clásico de 400g de la mejor carne argentina.',
    price: 12000,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    imageId: 'parrilla-2',
    categoryId: 'cat2',
    isVisible: true,
    inStock: true,
    isSpecial: false,
    tags: ['sin TACC'],
    allergens: [],
    searchKeywords: ['bife', 'chorizo', 'carne', 'parrilla', 'asado'],
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item4',
    name: 'Picaña',
    description: 'Nuestro corte especial. Tapa de cuadril de 500g, tierna y sabrosa.',
    price: 15000,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageId: 'parrilla-1',
    categoryId: 'cat2',
    isVisible: true,
    inStock: true,
    isSpecial: true,
    tags: ['Especial', 'sin TACC'],
    allergens: [],
    searchKeywords: ['picaña', 'carne', 'tapa de cuadril', 'parrilla', 'especial'],
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item5',
    name: 'Ojo de Bife',
    description: 'Rib eye jugoso y marmolado de 450g.',
    price: 13500,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/202/600/400',
    imageId: 'parrilla-3',
    categoryId: 'cat2',
    isVisible: true,
    inStock: false,
    isSpecial: false,
    tags: ['Sin stock', 'sin TACC'],
    allergens: [],
    searchKeywords: ['ojo de bife', 'rib eye', 'carne', 'parrilla'],
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Acompañamientos
  {
    id: 'item6',
    name: 'Papas Fritas a Caballo',
    description: 'Papas fritas caseras con dos huevos fritos.',
    price: 3500,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/203/600/400',
    imageId: 'acompanamiento-2',
    categoryId: 'cat3',
    isVisible: true,
    inStock: true,
    isSpecial: false,
    tags: ['veggie'],
    allergens: ['huevo'],
    searchKeywords: ['papas fritas', 'guarnicion', 'a caballo'],
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'item7',
    name: 'Ensalada Mixta',
    description: 'Lechuga, tomate y cebolla con aderezos clásicos.',
    price: 3000,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/104/600/400',
    imageId: 'acompanamiento-1',
    categoryId: 'cat3',
    isVisible: true,
    inStock: true,
    isSpecial: false,
    tags: ['sin TACC', 'veggie'],
    allergens: [],
    searchKeywords: ['ensalada', 'mixta', 'fresca', 'saludable'],
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  // Postres
  {
    id: 'item8',
    name: 'Flan Casero',
    description: 'Flan tradicional con dulce de leche y crema chantilly.',
    price: 4000,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/105/600/400',
    imageId: 'postre-1',
    categoryId: 'cat4',
    isVisible: true,
    inStock: true,
    isSpecial: false,
    tags: ['sin TACC', 'veggie'],
    allergens: ['lacteos', 'huevo'],
    searchKeywords: ['flan', 'postre', 'dulce de leche', 'casero'],
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
    // Vinos
  {
    id: 'item9',
    name: 'Rutini Malbec',
    description: 'Vino tinto de alta gama, ideal para acompañar carnes rojas.',
    price: 18000,
    currency: 'ARS',
    imageUrl: 'https://picsum.photos/seed/106/600/400',
    imageId: 'vino-1',
    categoryId: 'cat6',
    isVisible: true,
    inStock: true,
    isSpecial: false,
    tags: [],
    allergens: [],
    searchKeywords: ['vino', 'tinto', 'malbec', 'rutini'],
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
